### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by laurencefass** [wodby/drupal-node#1]
this is a support request. i want to use your image but my docker knowledge is somewhat limited at present.
  
i have pulled the image from docker. what do i do with it? do i have to configure anything? are there any recommended docker run parameters to set it up? does the image run node, drupal, mysql and everything else it needs in a single container?

what do i expect on running the container? is it a running system? do i need to install or configure drupal? anything else?

also: what steps/commands to do use to build from a clone of the repo to create exactly the same image on docker hub?

thanks

**Comment by csandanov** [comment]
See [docker4drupal](https://github.com/wodby/docker4drupal) and its [quick start](https://wodby.com/stacks/drupal/docs/local/quick-start/) quide

For drupal's nodejs integration container see https://wodby.com/stacks/drupal/docs/containers/nodejs/

**Comment by laurencefass** [comment]
the instructions are:
    _Install Node.js Integration Drupal module on your site
    Visit the Node.js configuration page under the Configuration menu, and enter the connection information for your Node.js server application. Set host to node and service key can be found on [Instance] > Stack > Node.js__

is this a container only for drupal?
do i need to install separate node.js server?

what is [Instance] > Stack > Node.js?

thanks

**Comment by csandanov** [comment]
it's a container for [node.js app server](https://github.com/beejeebus/drupal-nodejs) required by https://www.drupal.org/project/nodejs module. You don't need any additional node.js servers. 

> what is [Instance] > Stack > Node.js?

Those are instructions if you deploy Drupal app via Wodby, ignore it if you don't. You can just set `NODE_SERVICE_KEY` to any value as you can see it's [done in d4d's compose file](https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml#L159)
