### ISSUE TITLE
New version drupal-node.js

### ISSUE THREAD

**Issue by doidd** [wodby/drupal-node#2]
Drupal module **Node.js integration** and node js package drupal-node.js have new version (1.0.11). But this image still using version 1.0.10. New version Node.js integration only working right with drupal-node.js 1.0.11. So, can you help me add new image of instance or the way config DRUPAL_NODE_VER in file .env?

**Comment by csandanov** [comment]
I see 1.0.10 on https://github.com/beejeebus/drupal-nodejs/releases which README recommends as the source
