### ISSUE TITLE
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules

### ISSUE THREAD

**Issue by divined** [wodby/drupal-node#3]
command: sh -c 'npm install && npm install -g bower && bower install && npm install -g grunt && grunt'
I need bower and grunt in my project, but i get:
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules

**Comment by csandanov** [comment]
There's no point to install something globally, just skip `-g` flag. Also, you probably need `wodby/node` image, which is a generic node image.

**Comment by divined** [comment]
grunt and bower don't work without global installation ((
// -> Local Npm module "grunt-cli" not found. Is it installed?
wodby/node - doesn't have python ((

**Comment by divined** [comment]
Node.js have a lot of packages which must be installed globally, and will not work without it!!

**Comment by csandanov** [comment]
then just access the container as root

**Comment by divined** [comment]
it is not a right solution, then all files created by grunt become unavailable by local user

**Comment by csandanov** [comment]
You're right, I've released wodby/node 0.11.2 with the changed global npm directory to resolve permissions issue, please let me know if that helped.
