### ISSUE TITLE
Missing C compilers and configurators 

### ISSUE THREAD

**Issue by kobs30** [wodby/drupal-node#4]
/bin/sh: autoreconf: not found
configure: error: no acceptable C compiler found in $PATH

A lot of modules requires it: jpegtran-bin, optipng-bin, gifsicle ...

**Comment by kobs30** [comment]
FROM wodby/node:12-0.28.1

USER root

RUN set -ex; \
    \
    apk add --update pkgconfig autoconf automake libtool nasm build-base zlib-dev;

USER node

**Comment by csandanov** [comment]
You're probably looking for https://github.com/wodby/node, it has `-dev` tags with full sudo permissions to install additional packages
